"""Demo-data seeder for README recording sessions (issue #313).

Populates a throwaway user-data directory with a believable demo pipeline so
the README hero GIF / screenshot session has fully-rendered UI without any
real personal data.

Usage:
    uv run python scripts/seed_demo_data.py --dir <path>

Then boot the app against that dir:
    JOB_CANNON_USER_DATA_DIR=<path> uv run job-cannon

Safety guards:
  - Refuses to run if --dir resolves to the repo root (CWD check).
  - Refuses to run if --dir contains a jobs.db NOT created by this script
    (sentinel marker file .demo_seed is absent).
  - Idempotent: re-running against a previously-seeded dir resets to clean state.
"""

from __future__ import annotations

import argparse
import json
import os
import sqlite3
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path

# ---------------------------------------------------------------------------
# Sentinel marker file — written to the target dir on first seed.
# ---------------------------------------------------------------------------
_SENTINEL = ".demo_seed"

# ---------------------------------------------------------------------------
# Minimal config — all paid sources disabled, scoring provider stubbed.
# ---------------------------------------------------------------------------
_DEMO_CONFIG_YAML_TEMPLATE = """\
# Demo configuration generated by scripts/seed_demo_data.py
# DO NOT use for real job searching — all paid sources are disabled.

profile:
  target_titles:
    - Senior Data Scientist
    - Staff Data Scientist
    - Principal Data Scientist
  target_locations:
    - Remote
  min_salary: 140000
  industries:
    - Tech
    - SaaS
    - Fintech
  exclusions:
    title_keywords:
      - intern
      - junior
    companies: []
  skills:
    - Python
    - SQL
    - Machine Learning
    - Statistics
  job_archetypes:
    ml_engineering:
      keywords: ["machine learning", "ml", "model serving"]
      weight_overrides: {}
    analytics_lead:
      keywords: ["analytics", "experimentation", "stakeholder"]
      weight_overrides: {}

sources:
  imap:
    enabled: false
    host: imap.gmail.com
    port: 993
    email: ""
    app_password: ""
    folder: INBOX
  gmail:
    enabled: false
    lookback_days: 7
    senders:
      linkedin_alerts: jobalerts-noreply@linkedin.com
      linkedin_jobs: jobs-noreply@linkedin.com
      glassdoor: noreply@glassdoor.com
      indeed: alert@indeed.com
      ziprecruiter: no-reply@ziprecruiter.com
  serpapi:
    enabled: false
    api_key: ""
    max_pages: 1
    queries:
      - query: Data Scientist
        location: Remote
  thordata:
    enabled: false
    api_key: ""
    max_age_days: 3
    queries:
      - query: Data Scientist
        location: Remote
  dataforseo:
    enabled: false
    api_key: ""
    depth: 10
    max_age_days: 7
    priority: 1
    poll_interval_seconds: 0
    poll_timeout_seconds: 60
    queries:
      - query: Data Scientist
        location: Remote
  portal_search:
    enabled: false
    keywords:
      - Data Scientist
    max_serp_queries: 0
    jobicy:
      enabled: false
    yc_workatastartup:
      enabled: false
    usajobs:
      enabled: false
      user_agent_email: ""
      authorization_key: ""
    adzuna:
      enabled: false
      app_id: ""
      app_key: ""
      country: us
    jooble:
      enabled: false
      api_key: ""
  google_cse:
    enabled: false
    api_key: ""
    cse_id: ""

scoring:
  weights:
    title_match: 0.3
    seniority_alignment: 0.2
    location_fit: 0.15
    salary_range: 0.15
    industry_relevance: 0.1
    company_signals: 0.05
    recency: 0.05
  min_score_threshold: 40
  low_signal_jd_chars: 1500
  daily_budget_usd: 0.0
  candidate_score_threshold: 55
  prompt_variant: baseline

providers:
  primary: ollama
  fallback_chain: []
  overrides: {}
  daily_limits: {}
  throttle_delays: {}

db:
  path: "{db_path}"

careers_crawl:
  enabled: false
  freshness_days: 1
  max_workers: 1
  max_load_more_clicks: 2
  max_pagination_pages: 2
  interactive_enabled: false

ats:
  scan_enabled: false
  scan_days: mon,fri
  scan_hour: 8
  high_score_history_threshold: 20
  identity_reconcile:
    enabled: false
    shadow: true
    max_unique_urls_per_company: 10
    max_companies_per_promote_run: 10

scheduler:
  cadence_preset: light

agentic:
  batch_limit: 0

server:
  host: "127.0.0.1"
  port: 5001
  debug: false

staleness:
  enabled: false
  batch_ats_enabled: false
  cascade_recheck_days: 30
  cascade_parallel_workers: 1
  cascade_request_timeout_seconds: 5

filters:
  company_denylist: []

autoheal:
  heal_enabled: false
  heal_provider: quick
  heal_max_attempts: 3
  heal_backoff_hours: 24
  validate_timeout_s: 30
"""

# ---------------------------------------------------------------------------
# Fictional demo jobs — 40 rows, ~15 fictional companies.
# None of these are real employers or copied from any real listing.
# ---------------------------------------------------------------------------
_NOW_UTC = datetime.now(UTC).replace(tzinfo=None)


def _ts(days_ago: float, hours_offset: float = 0.0) -> str:
    """Return a naive UTC ISO timestamp N days (and optionally hours) ago."""
    delta = timedelta(days=days_ago, hours=hours_offset)
    return (_NOW_UTC - delta).isoformat(timespec="seconds")


# Sub-score keys must match _SUB_SCORE_KEYS in job_finder/db/_classification.py
_SCORE_KEYS = (
    "title_fit",
    "location_fit",
    "comp_fit",
    "domain_match",
    "seniority_match",
    "skills_match",
)


def _sub_scores(tf: int, lf: int, cf: int, dm: int, sm: int, sk: int) -> dict:
    """Build a sub_scores dict with the canonical key order."""
    return dict(zip(_SCORE_KEYS, [tf, lf, cf, dm, sm, sk], strict=True))


def _rationale(strengths: list[str], gaps: list[str]) -> dict:
    """Build the rationale/fit_analysis dict expected by the templates."""
    return {
        "strengths": strengths,
        "gaps": gaps,
        "talking_points": [
            "Emphasise previous impact metrics when discussing this role.",
            "Highlight cross-functional collaboration experience.",
        ],
        "resume_priority_skills": ["Python", "SQL", "A/B testing", "causal inference"],
    }


def _derive_classification(sub_scores: dict) -> str:
    """Mirror derive_classification logic (no legitimacy_note, no low_signal path)."""
    vals = list(sub_scores.values())
    if any(v == 1 for v in vals):
        return "reject"
    if all(v >= 3 for v in vals):
        return "apply"
    if all(v >= 2 for v in vals):
        return "consider"
    return "skip"


# Each entry: (dedup_key, title, company, location, description, jd_full,
#              sub_scores, pipeline_status, salary_min, salary_max, first_seen_days_ago)
_DEMO_JOBS: list[tuple] = [
    # --- APPLY-band jobs (all axes ≥ 3) ---
    (
        "demo_nexalytix_sr_ds_001",
        "Senior Data Scientist – Growth",
        "Nexalytix",
        "Remote",
        "Nexalytix builds revenue intelligence tooling for mid-market SaaS.",
        "We are looking for a Senior Data Scientist to join the Growth team at Nexalytix. "
        "You will design and run experimentation frameworks, build causal inference models, "
        "and partner closely with product and engineering to ship data-informed features. "
        "Requirements: 4+ years in an applied data science role, strong Python and SQL, "
        "experience with A/B testing at scale, and comfort presenting to C-suite. "
        "Compensation: $160k–$200k base + equity + remote-first. We are headquartered in "
        "Austin but the entire data team is distributed across North America.",
        _sub_scores(5, 5, 4, 4, 4, 4),
        "reviewing",
        160000,
        200000,
        1.2,
    ),
    (
        "demo_vantaflow_staff_ds_002",
        "Staff Data Scientist",
        "Vantaflow",
        "Remote (US)",
        "Vantaflow provides supply-chain analytics for mid-market retailers.",
        "Vantaflow is hiring a Staff Data Scientist to own our forecasting platform. "
        "You will lead a team of 3 ICs, define the modeling roadmap, and translate "
        "complex findings for non-technical stakeholders. We operate at tens of millions "
        "of rows daily. Stack: Python, dbt, Snowflake, Spark. Salary band $180k–$220k. "
        "Fully remote, US time zones. 5+ years required; staff-level ownership mindset essential.",
        _sub_scores(5, 5, 5, 5, 4, 4),
        "applied",
        180000,
        220000,
        2.5,
    ),
    (
        "demo_quorbit_principal_ds_003",
        "Principal Data Scientist, Recommendations",
        "Quorbit",
        "Remote",
        "Quorbit is a personalization infrastructure company serving streaming platforms.",
        "We are looking for a Principal Data Scientist to own the recommendations vertical. "
        "Key responsibilities: build and iterate on collaborative filtering and two-tower "
        "retrieval models, define evaluation metrics, mentor junior scientists. "
        "You will have a large impact on real-time ranking pipelines serving hundreds of "
        "millions of recommendations per day. Ideal candidate: 7+ years, PhD preferred, "
        "deep experience with PyTorch, Python, Spark, MLflow. Remote, $200k–$240k.",
        _sub_scores(4, 5, 5, 5, 5, 4),
        "reviewing",
        200000,
        240000,
        0.5,
    ),
    (
        "demo_meridianai_sr_ds_004",
        "Senior Data Scientist – Marketing Analytics",
        "Meridian AI",
        "Remote, US",
        "Meridian AI builds LLM-powered marketing automation for e-commerce brands.",
        "The Senior Data Scientist on our Marketing Analytics team will own MMM modelling, "
        "attribution analysis, and incrementality testing. You will work with petabyte-scale "
        "clickstream data, build Bayesian marketing mix models, and present recommendations "
        "to CMOs of our enterprise clients. Requirements: strong Python, causal inference, "
        "experience with pymc or stan. Salary $155k–$195k, fully remote.",
        _sub_scores(4, 5, 4, 4, 4, 4),
        "discovered",
        155000,
        195000,
        0.8,
    ),
    (
        "demo_pulsar_sr_ds_005",
        "Senior Data Scientist, Fraud & Risk",
        "Pulsar Financial",
        "Remote",
        "Pulsar Financial offers real-time fraud detection for digital payments.",
        "We need a Senior Data Scientist to improve our fraud models. Day-to-day: "
        "iterate on gradient-boosting classifiers, design features from transaction graphs, "
        "run champion/challenger experiments, and collaborate with operations to close "
        "feedback loops. Experience with imbalanced classification and model monitoring "
        "required. Python, SQL, PySpark. $150k–$185k. Remote, US only.",
        _sub_scores(4, 5, 4, 4, 4, 5),
        "discovered",
        150000,
        185000,
        1.0,
    ),
    (
        "demo_heliostream_sr_mle_006",
        "Senior ML Engineer",
        "Heliostream",
        "Remote",
        "Heliostream provides real-time video analytics for the broadcasting industry.",
        "Join Heliostream as a Senior ML Engineer to productionise computer vision models. "
        "You will design model-serving infrastructure (Triton / TorchServe), instrument "
        "latency SLOs, and collaborate closely with the science team on model compression. "
        "Requirements: proficiency in Python, Kubernetes, ONNX, familiarity with MLOps "
        "platforms. $165k–$205k, remote.",
        _sub_scores(3, 5, 4, 4, 4, 4),
        "discovered",
        165000,
        205000,
        1.5,
    ),
    (
        "demo_catayst_analytics_lead_007",
        "Analytics Lead",
        "Catalyst Labs",
        "Remote, US/Canada",
        "Catalyst Labs builds product analytics infrastructure for B2B SaaS companies.",
        "Catalyst Labs is looking for an Analytics Lead to oversee a team of 4 analysts, "
        "own our data model and dashboard suite, define self-serve analytics standards, "
        "and partner with product management on OKR reviews. Strong SQL, dbt, Looker or "
        "Tableau required. Python a plus. 6+ years analytics experience. $145k–$175k. Remote.",
        _sub_scores(3, 5, 3, 3, 4, 3),
        "discovered",
        145000,
        175000,
        2.0,
    ),
    (
        "demo_tempoviz_sr_ds_008",
        "Senior Data Scientist – Time-Series Forecasting",
        "TempoViz",
        "Remote",
        "TempoViz provides demand forecasting for logistics and cold-chain operators.",
        "Seeking a Senior Data Scientist with deep expertise in time-series modelling. "
        "You will own our forecasting engine (Prophet, NHiTS, TFT), run backtesting pipelines, "
        "and ship models to production via our Python/FastAPI serving layer. Experience "
        "with hierarchical forecasting and probabilistic intervals required. $155k–$190k. Remote.",
        _sub_scores(4, 5, 4, 5, 4, 4),
        "discovered",
        155000,
        190000,
        0.3,
    ),
    (
        "demo_synapse_sr_ds_009",
        "Senior Data Scientist, Experimentation Platform",
        "Synapse Cloud",
        "Remote (Global)",
        "Synapse Cloud is a cloud infrastructure startup serving developer tooling.",
        "We are scaling our experimentation platform and need a Senior Data Scientist to "
        "own statistical methodology, build variance-reduction techniques (CUPED, stratification), "
        "and make the platform self-serve for product teams. Strong statistics background required. "
        "Python, SQL, PySpark. $160k–$200k. Remote-first, global team.",
        _sub_scores(4, 5, 4, 4, 4, 4),
        "discovered",
        160000,
        200000,
        3.0,
    ),
    (
        "demo_verdant_sr_ds_010",
        "Senior Data Scientist – Climate Risk",
        "Verdant Analytics",
        "Remote",
        "Verdant Analytics delivers climate-risk scoring to insurance carriers.",
        "Looking for a Senior Data Scientist to build geospatial risk models. You'll work with "
        "satellite imagery, flood-plain data, and actuarial loss records to train predictive "
        "models that price insurance risk. Strong Python (geopandas, rasterio), spatial SQL, "
        "gradient boosting. $155k–$190k. Remote.",
        _sub_scores(3, 5, 4, 4, 4, 4),
        "discovered",
        155000,
        190000,
        2.2,
    ),
    # --- CONSIDER-band jobs (all axes ≥ 2, at least one = 2) ---
    (
        "demo_oraculum_ds_011",
        "Data Scientist – Growth Analytics",
        "Oraculum",
        "San Francisco, CA (Hybrid)",
        "Oraculum is an early-stage fintech building AI-driven credit underwriting.",
        "Data Scientist role focused on growth analytics at Oraculum. Work with lifecycle "
        "cohort models, retention analyses, and channel attribution. Mid-level IC role. "
        "Strong SQL required; Python a plus. On-site 3 days/week in SF. $130k–$160k.",
        _sub_scores(3, 2, 3, 3, 3, 3),
        "discovered",
        130000,
        160000,
        1.8,
    ),
    (
        "demo_lattice_ds_012",
        "Data Scientist, Pricing Models",
        "LatticeOps",
        "New York, NY (Hybrid)",
        "LatticeOps is a B2B SaaS pricing intelligence platform.",
        "Join the LatticeOps data team as a Data Scientist focused on dynamic pricing models. "
        "You will build regression and causal models to estimate price elasticity, run pricing "
        "experiments, and present findings to the pricing committee. Strong statistics, Python, R. "
        "$135k–$165k. Hybrid NYC, 2 days/week in office.",
        _sub_scores(3, 2, 3, 4, 3, 3),
        "discovered",
        135000,
        165000,
        4.0,
    ),
    (
        "demo_auris_ds_013",
        "Data Scientist – NLP",
        "Auris Intelligence",
        "Remote, US",
        "Auris Intelligence builds voice-of-customer analytics for enterprise.",
        "Seeking a Data Scientist with NLP expertise to improve our text classification "
        "and topic modelling pipelines. HuggingFace, spaCy, Python required. Experience "
        "with LLM prompt engineering a plus. $140k–$175k. Remote.",
        _sub_scores(3, 5, 3, 3, 2, 3),
        "discovered",
        140000,
        175000,
        0.9,
    ),
    (
        "demo_ironwood_ds_014",
        "Data Scientist, Supply Chain",
        "Ironwood Analytics",
        "Chicago, IL (Hybrid 3x)",
        "Ironwood Analytics provides procurement analytics for industrial manufacturers.",
        "Data Scientist to build demand and supply mismatch models. Strong SQL, Python, "
        "optimization familiarity helpful (PuLP / OR-Tools). In-office 3 days/week Chicago. "
        "$128k–$158k.",
        _sub_scores(3, 2, 3, 3, 3, 3),
        "discovered",
        128000,
        158000,
        3.5,
    ),
    (
        "demo_luminos_sr_analyst_015",
        "Senior Data Analyst",
        "Luminos Health",
        "Remote (US)",
        "Luminos Health is a health-tech startup building care-quality dashboards.",
        "Senior Data Analyst to own executive reporting, build KPI dashboards in Looker, "
        "and support product analytics. Strong SQL, Looker/Tableau. Python helpful. "
        "$115k–$145k. Remote.",
        _sub_scores(2, 5, 2, 3, 3, 3),
        "discovered",
        115000,
        145000,
        1.4,
    ),
    (
        "demo_catalytic_ds_016",
        "Data Scientist – Personalisation",
        "Catalytic Media",
        "Hybrid, Los Angeles",
        "Catalytic Media is an ad-tech startup building contextual targeting for OTT.",
        "Seeking a mid-level Data Scientist to own personalisation models for connected TV ads. "
        "Experience with collaborative filtering, Python, and Spark. Strong interest in "
        "causal ML preferred. Hybrid LA, 2 days/week. $140k–$170k.",
        _sub_scores(3, 2, 3, 3, 3, 3),
        "discovered",
        140000,
        170000,
        2.8,
    ),
    (
        "demo_phaedra_sr_ds_017",
        "Senior Data Scientist – Lifecycle",
        "Phaedra Technologies",
        "Remote",
        "Phaedra Technologies builds cloud-based customer data platforms for B2C brands.",
        "We're hiring a Senior Data Scientist to lead lifecycle modelling (propensity, LTV, "
        "churn prediction). You'll own the modelling pipeline end-to-end and mentor 2 junior "
        "scientists. Python, SQL, mlflow. $150k–$180k. Remote. The role requires some "
        "travel to client sites (up to 15%).",
        _sub_scores(4, 5, 3, 3, 4, 3),
        "discovered",
        150000,
        180000,
        1.1,
    ),
    (
        "demo_axiom_sr_ds_018",
        "Senior Data Scientist – Ads Relevance",
        "Axiom Digital",
        "Hybrid, Seattle",
        "Axiom Digital is an independent ad-exchange serving mid-market publishers.",
        "Senior Data Scientist to improve our ad relevance ranking. Experience with "
        "feature engineering for click-through-rate models, online A/B experimentation, "
        "and Python/Spark required. Hybrid Seattle, 3 days. $155k–$195k.",
        _sub_scores(3, 2, 4, 3, 3, 4),
        "discovered",
        155000,
        195000,
        0.7,
    ),
    # --- LOW-SIGNAL or REJECT-band jobs ---
    (
        "demo_obscura_ds_019",
        "Data Scientist",
        "Obscura Ventures",
        "On-site, Denver",
        "Obscura Ventures is a seed-stage startup in stealth mode.",
        "Looking for a Data Scientist. Must be on-site in Denver. Details TBD.",
        _sub_scores(3, 1, 2, 2, 2, 2),
        "discovered",
        None,
        None,
        4.5,
    ),
    (
        "demo_nyx_jr_ds_020",
        "Junior Data Scientist",
        "Nyx Analytics",
        "Remote",
        "Nyx Analytics provides dashboards for small business.",
        "Entry-level Data Scientist position. 0-2 years experience. Python basics. $65k–$80k.",
        _sub_scores(1, 5, 1, 3, 1, 2),
        "archived",
        65000,
        80000,
        5.0,
    ),
    # --- More apply/consider jobs to round out 40 ---
    (
        "demo_crestline_sr_ds_021",
        "Senior Data Scientist, Platform Health",
        "Crestline Technologies",
        "Remote",
        "Crestline Technologies operates observability infrastructure for cloud-native apps.",
        "Join Crestline to build anomaly detection and SLO forecasting models for our "
        "infrastructure monitoring platform. We process ~5TB of telemetry daily. "
        "Python, SQL, probabilistic modelling, Spark. $158k–$198k. Fully remote.",
        _sub_scores(4, 5, 4, 4, 4, 4),
        "discovered",
        158000,
        198000,
        1.3,
    ),
    (
        "demo_aurelia_sr_ds_022",
        "Senior Data Scientist – Search Ranking",
        "Aurelia Commerce",
        "Remote",
        "Aurelia Commerce is an enterprise search-as-a-service platform.",
        "We are hiring a Senior Data Scientist to own learning-to-rank models. "
        "Experience with LambdaMART, LightGBM, NDCG evaluation, and Elasticsearch. "
        "Python, SQL. $160k–$200k. Remote-first.",
        _sub_scores(4, 5, 4, 4, 4, 5),
        "discovered",
        160000,
        200000,
        2.4,
    ),
    (
        "demo_novex_ds_023",
        "Data Scientist – Demand Forecasting",
        "Novex Logistics",
        "Remote (US/EU)",
        "Novex Logistics provides last-mile optimisation for parcel carriers.",
        "Data Scientist to own demand forecasting models feeding into our routing engine. "
        "Prophet/NHiTS experience helpful. Strong Python, SQL, Airflow. "
        "$145k–$180k. Remote, US or EU timezones.",
        _sub_scores(4, 5, 4, 5, 3, 4),
        "discovered",
        145000,
        180000,
        0.6,
    ),
    (
        "demo_tessera_sr_ds_024",
        "Senior Data Scientist, Trust & Safety",
        "Tessera Network",
        "Remote",
        "Tessera Network operates a creator marketplace for digital media.",
        "Senior Data Scientist to build content integrity classifiers, "
        "detect coordinated inauthentic behaviour, and design enforcement policies. "
        "Experience with graph ML, NLP, imbalanced datasets. Python, SQL. "
        "$155k–$195k. Remote.",
        _sub_scores(4, 5, 4, 4, 4, 4),
        "discovered",
        155000,
        195000,
        3.2,
    ),
    (
        "demo_cortex_sr_ds_025",
        "Senior Data Scientist – Pricing & Revenue",
        "Cortex Analytics",
        "Remote",
        "Cortex Analytics builds dynamic pricing models for SaaS companies.",
        "Own end-to-end pricing model development: price-elasticity estimation, cohort-based "
        "LTV projections, and bundle-optimisation experiments. Python, causal inference, "
        "Bayesian stats, SQL. $160k–$200k. Fully remote.",
        _sub_scores(4, 5, 4, 4, 4, 4),
        "discovered",
        160000,
        200000,
        1.7,
    ),
    (
        "demo_aethon_sr_ds_026",
        "Senior Data Scientist, Customer Intelligence",
        "Aethon Labs",
        "Remote",
        "Aethon Labs provides AI-driven CRM enrichment for B2B sales teams.",
        "We need a Senior Data Scientist to build customer-intelligence models: "
        "account scoring, expansion opportunity detection, churn risk. "
        "Python, SQL, Snowflake, scikit-learn. $150k–$185k. Remote.",
        _sub_scores(4, 5, 3, 4, 4, 4),
        "discovered",
        150000,
        185000,
        2.1,
    ),
    (
        "demo_zenith_sr_ds_027",
        "Senior Data Scientist – Fintech Risk",
        "Zenith Risk",
        "Remote",
        "Zenith Risk is a credit-risk analytics platform for alternative lenders.",
        "Build and validate credit underwriting models, design monitoring dashboards "
        "for model drift, and work closely with the compliance team. "
        "Python, SQL, XGBoost, Shapley values, regulatory awareness. "
        "$160k–$200k. Remote.",
        _sub_scores(4, 5, 4, 4, 4, 4),
        "discovered",
        160000,
        200000,
        0.4,
    ),
    (
        "demo_polaris_sr_ds_028",
        "Senior Data Scientist, Marketplace",
        "Polaris Market",
        "Remote, US",
        "Polaris Market operates a B2B procurement marketplace for mid-market companies.",
        "Senior Data Scientist to build dynamic matching algorithms and pricing models "
        "for our two-sided marketplace. Game-theory familiarity a bonus. "
        "Python, SQL, MLflow. $155k–$190k. Remote, US.",
        _sub_scores(4, 5, 4, 4, 4, 4),
        "discovered",
        155000,
        190000,
        1.9,
    ),
    (
        "demo_arc_sr_ds_029",
        "Senior Data Scientist – MLOps",
        "Arc Platform",
        "Remote",
        "Arc Platform builds end-to-end MLOps tooling for enterprise teams.",
        "Senior Data Scientist to own the model lifecycle across training, deployment, "
        "and monitoring. Work closely with ML engineers on feature stores, experiment "
        "tracking, and drift detection. Python, Kubeflow, MLflow, dbt. "
        "$158k–$198k. Remote.",
        _sub_scores(3, 5, 4, 4, 4, 5),
        "discovered",
        158000,
        198000,
        2.7,
    ),
    (
        "demo_luminary_sr_ds_030",
        "Staff Data Scientist – Core Ranking",
        "Luminary Labs",
        "Remote (US)",
        "Luminary Labs is an AI-first search startup building semantic retrieval for enterprise.",
        "Own core ranking models: bi-encoder retrieval, cross-encoder re-ranking, "
        "query-intent classification. Production inference at low latency. "
        "PyTorch, HuggingFace, Triton, Python. $185k–$230k. Remote, US.",
        _sub_scores(5, 5, 5, 5, 4, 5),
        "reviewing",
        185000,
        230000,
        0.2,
    ),
    (
        "demo_dawnrise_sr_ds_031",
        "Senior Data Scientist, Developer Analytics",
        "Dawnrise",
        "Remote",
        "Dawnrise builds code-quality analytics for engineering organisations.",
        "Build models to detect engineering bottlenecks, predict cycle time, "
        "and recommend workflow improvements. Strong Python, graph analysis, "
        "NLP for code comments. $150k–$185k. Remote.",
        _sub_scores(3, 5, 4, 4, 3, 4),
        "discovered",
        150000,
        185000,
        3.4,
    ),
    (
        "demo_fluxor_sr_ds_032",
        "Senior Data Scientist – Energy Forecasting",
        "Fluxor Energy",
        "Remote (US)",
        "Fluxor Energy provides grid-edge analytics to renewable energy operators.",
        "Forecast solar and wind generation at 15-minute resolution for grid operators. "
        "Physics-informed ML, uncertainty quantification, time-series expertise. "
        "Python (NumPy, SciPy, PyTorch). $155k–$195k. Remote, US.",
        _sub_scores(4, 5, 4, 4, 4, 4),
        "discovered",
        155000,
        195000,
        1.6,
    ),
    (
        "demo_kepler_sr_ds_033",
        "Senior Data Scientist, Observability",
        "Kepler Systems",
        "Remote",
        "Kepler Systems provides AI-assisted incident management for SRE teams.",
        "Build anomaly detection and root-cause isolation models feeding our incident "
        "correlation engine. Experience with streaming ML, time-series, and Kafka. "
        "Python, SQL. $160k–$200k. Remote.",
        _sub_scores(4, 5, 4, 4, 4, 4),
        "discovered",
        160000,
        200000,
        4.2,
    ),
    (
        "demo_sienna_ds_034",
        "Data Scientist – Clinical Trials",
        "Sienna Bioanalytics",
        "Remote, US",
        "Sienna Bioanalytics provides statistical analytics to pharma clinical programs.",
        "Build survival-analysis, mixed-effects, and power-calculation models. "
        "Strong R or Python (lifelines, statsmodels). Domain knowledge in clinical trials helpful. "
        "$145k–$180k. Remote.",
        _sub_scores(3, 5, 3, 3, 3, 3),
        "discovered",
        145000,
        180000,
        2.6,
    ),
    (
        "demo_gridline_sr_ds_035",
        "Senior Data Scientist – Supply Chain Intelligence",
        "Gridline Commerce",
        "Remote",
        "Gridline Commerce provides inventory and demand intelligence to e-commerce brands.",
        "Build demand sensing models, safety-stock optimisers, and replenishment forecasters. "
        "Python, SQL, Airflow. Experience with multi-echelon inventory models a strong plus. "
        "$155k–$190k. Fully remote.",
        _sub_scores(4, 5, 4, 5, 4, 4),
        "discovered",
        155000,
        190000,
        1.0,
    ),
    (
        "demo_praxis_sr_ds_036",
        "Senior Data Scientist – Retention",
        "Praxis SaaS",
        "Remote",
        "Praxis SaaS is a project management tool competing in the mid-market segment.",
        "Own retention modelling, build early-warning churn signals, and run "
        "intervention experiments. Python, SQL, causal ML. $150k–$185k. Remote.",
        _sub_scores(4, 5, 3, 3, 4, 4),
        "discovered",
        150000,
        185000,
        3.8,
    ),
    (
        "demo_echo_sr_ds_037",
        "Senior Data Scientist – Voice AI",
        "Echo AI",
        "Remote",
        "Echo AI builds conversational intelligence software for call-centre automation.",
        "Build entity extraction, intent classification, and sentiment models for "
        "real-time speech streams. HuggingFace, Python, ONNX, streaming inference. "
        "$158k–$198k. Fully remote.",
        _sub_scores(4, 5, 4, 4, 4, 4),
        "discovered",
        158000,
        198000,
        2.3,
    ),
    (
        "demo_navari_sr_ds_038",
        "Senior Data Scientist, Self-Serve Analytics",
        "Navari",
        "Remote",
        "Navari provides embedded analytics for B2B vertical SaaS platforms.",
        "Own the data model, metric definitions, and anomaly-detection layer "
        "powering our customers' self-serve dashboards. SQL, Python, dbt, Metabase. "
        "$148k–$183k. Remote.",
        _sub_scores(3, 5, 3, 3, 4, 3),
        "discovered",
        148000,
        183000,
        0.8,
    ),
    (
        "demo_tandem_sr_ds_039",
        "Senior Data Scientist – Financial Forecasting",
        "Tandem Finance",
        "Remote (US/Canada)",
        "Tandem Finance builds FP&A automation for mid-market CFO teams.",
        "Build probabilistic financial-forecasting models (Monte Carlo, Bayesian "
        "structural time series), automate variance analysis, and partner with "
        "product to ship AI-assisted budgeting. Python, SQL. $155k–$195k. Remote.",
        _sub_scores(4, 5, 4, 4, 4, 4),
        "discovered",
        155000,
        195000,
        1.5,
    ),
    (
        "demo_velo_ds_consider_040",
        "Data Scientist",
        "Velo Dynamics",
        "Hybrid, Austin TX",
        "Velo Dynamics provides logistics-optimisation software for trucking fleets.",
        "Data Scientist to improve our route-optimisation models. Hybrid Austin. "
        "Strong Python and SQL required. Optimisation familiarity (OR-Tools, PuLP) helpful. "
        "$130k–$160k.",
        _sub_scores(3, 2, 3, 4, 3, 3),
        "discovered",
        130000,
        160000,
        4.8,
    ),
]


def _check_guard(target: Path) -> None:
    """Refuse to seed if the target looks like the repo root or a real user dir."""
    # Guard 1: refuse if target is the CWD (likely the repo root).
    try:
        cwd = Path.cwd().resolve()
        resolved = target.resolve()
        if resolved == cwd:
            print(
                f"ERROR: --dir resolves to the current working directory ({resolved}).\n"
                "Refusing to seed: this is likely your repo root.",
                file=sys.stderr,
            )
            sys.exit(1)
    except Exception:
        pass

    # Guard 2: if a jobs.db exists but the sentinel is absent, this is real user data.
    db_file = target / "jobs.db"
    sentinel_file = target / _SENTINEL
    if db_file.exists() and not sentinel_file.exists():
        print(
            f"ERROR: {db_file} exists but {sentinel_file} is absent.\n"
            "Refusing to overwrite: this directory appears to contain real user data.\n"
            "To force a fresh seed in a new directory, delete the directory and re-run.",
            file=sys.stderr,
        )
        sys.exit(1)


def _write_config(target: Path) -> None:
    """Write the minimal demo config.yaml with an absolute db path."""
    config_file = target / "config.yaml"
    # Use forward slashes so YAML is valid on all platforms.
    db_path_str = str(target / "jobs.db").replace("\\", "/")
    # Escape literal {} in YAML values (e.g. weight_overrides: {}) before
    # calling .format() so only {db_path} is substituted.
    safe_template = _DEMO_CONFIG_YAML_TEMPLATE.replace("{}", "{{}}").replace(
        "{db_path}", "{db_path}"
    )
    content = safe_template.format(db_path=db_path_str)
    config_file.write_text(content, encoding="utf-8")


def _seed_db(db_path: str, target: Path) -> None:
    """Run migrations, wipe any prior demo seed, insert fresh demo rows."""
    # Import here so the script can be run from the repo root with uv run.
    from job_finder.web.db_helpers import standalone_connection
    from job_finder.web.db_migrate import run_migrations

    # run_migrations creates the schema up to current version.
    # Pass the target dir as user_data_root so migration 41's backup gate
    # (which checks for a recent backup file) uses the demo dir, not CWD.
    run_migrations(db_path, user_data_root=str(target))

    with standalone_connection(db_path) as conn:
        _wipe_demo_rows(conn)
        _insert_jobs(conn)
        _insert_costs(conn)
        _seed_onboarding_complete(conn)
        conn.commit()


def _wipe_demo_rows(conn: sqlite3.Connection) -> None:
    """Wipe all rows in preparation for a clean re-seed.

    This is a throwaway demo DB (the sentinel guards against real user data),
    so wiping all rows on re-seed is safe and produces the cleanest state.
    """
    conn.execute("DELETE FROM jobs")
    conn.execute("DELETE FROM scoring_costs")
    conn.commit()


def _insert_jobs(conn: sqlite3.Connection) -> None:
    """Insert all 40 fictional demo jobs."""
    now_str = datetime.now(UTC).replace(tzinfo=None).isoformat(timespec="seconds")

    for row in _DEMO_JOBS:
        (
            dedup_key,
            title,
            company,
            location,
            description,
            jd_full,
            sub_scores,
            pipeline_status,
            salary_min,
            salary_max,
            days_ago,
        ) = row

        classification = _derive_classification(sub_scores)
        sub_scores_json = json.dumps(sub_scores)

        strengths: list[str] = []
        gaps: list[str] = []

        # Build believable strengths/gaps from sub-scores
        score_comments = {
            "title_fit": (
                "Title aligns well with target role",
                "Title is an imperfect match for target level",
            ),
            "location_fit": (
                "Fully remote — strong location fit",
                "On-site / hybrid requirement is a constraint",
            ),
            "comp_fit": (
                "Salary band overlaps target range",
                "Compensation band is below target minimum",
            ),
            "domain_match": (
                "Domain closely matches prior experience",
                "Domain requires some ramp-up",
            ),
            "seniority_match": (
                "Seniority level matches target scope",
                "Seniority framing is slightly misaligned",
            ),
            "skills_match": (
                "Core technical stack matches skill set",
                "Some required tools are outside primary stack",
            ),
        }
        for key, val in sub_scores.items():
            positive, negative = score_comments.get(key, ("Strong signal", "Weak signal"))
            if val >= 4:
                strengths.append(positive)
            elif val <= 2:
                gaps.append(negative)

        rationale = _rationale(strengths or ["Role has interesting growth potential"], gaps)
        fit_analysis_json = json.dumps(rationale)

        first_seen = _ts(days_ago)
        last_seen = _ts(days_ago * 0.5)
        posted_date_str = _ts(days_ago + 0.5, hours_offset=2.0)[:10]  # date only

        # I-13 trigger fires on INSERT when jd_full is non-NULL and fails the
        # content-density gate (< 200 chars or junk prefix).  Insert NULL here
        # and UPDATE afterward so the trigger never sees a failing value.
        conn.execute(
            """
            INSERT OR REPLACE INTO jobs (
                dedup_key, title, company, location, sources, source_urls,
                source_id, salary_min, salary_max, salary_currency, salary_period,
                description, jd_full,
                first_seen, last_seen, score, score_breakdown,
                pipeline_status, posted_date, posted_date_precision, notes,
                fit_analysis, classification, sub_scores_json, scoring_model,
                scoring_provider,
                locations_raw, locations_structured, workplace_type,
                unresolved_reasons, enrichment_tier
            ) VALUES (
                ?, ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?,
                ?, NULL,
                ?, ?, ?, ?,
                ?, ?, ?, ?,
                ?, ?, ?, ?,
                ?,
                ?, ?, ?,
                ?, ?
            )
            """,
            (
                dedup_key,
                title,
                company,
                location,
                json.dumps(["demo_seed"]),  # sources
                json.dumps([f"https://jobs.example.com/{dedup_key}"]),  # source_urls
                dedup_key,  # source_id
                salary_min,
                salary_max,
                "USD",
                "annual",
                description,
                # jd_full intentionally omitted from VALUES (NULL literal above)
                first_seen,
                last_seen,
                0.0,  # score (v3 uses sub_scores; score column is legacy)
                json.dumps({}),  # score_breakdown
                pipeline_status,
                posted_date_str,
                "exact",  # posted_date_precision — synthetic demo dates (I-14)
                "",  # notes
                fit_analysis_json,
                classification,
                sub_scores_json,
                "demo_ollama",  # scoring_model
                "ollama",  # scoring_provider
                json.dumps([location]),  # locations_raw
                None,  # locations_structured
                "REMOTE" if "Remote" in location else "ONSITE",
                json.dumps([]),  # unresolved_reasons
                "mid",  # enrichment_tier
            ),
        )

        # Now UPDATE jd_full bypassing the INSERT trigger — the UPDATE trigger
        # (tg_jobs_jd_full_junk_upd) fires only when NEW.jd_full IS NOT NULL,
        # so NULL-to-NULL no-ops are safe.  Only update when the text is long
        # enough to pass the density gate (keeps reject/low-signal rows NULL).
        from job_finder.db._jd_full import _is_jd_junk as _jd_is_junk

        if jd_full and not _jd_is_junk(jd_full):
            conn.execute(
                "UPDATE jobs SET jd_full = ? WHERE dedup_key = ?",
                (jd_full, dedup_key),
            )


def _insert_costs(conn: sqlite3.Connection) -> None:
    """Insert a few ollama-attributed cost rows summing to $0.00."""
    now = datetime.now(UTC).replace(tzinfo=None)
    entries = [
        ("scoring", "demo_ollama", 2800, 450),
        ("scoring", "demo_ollama", 3100, 480),
        ("scoring", "demo_ollama", 2900, 460),
        ("quick", "demo_ollama", 1200, 200),
        ("quick", "demo_ollama", 1100, 190),
    ]
    for i, (purpose, model, in_tok, out_tok) in enumerate(entries):
        ts = (now - timedelta(hours=i * 2)).isoformat(timespec="seconds")
        conn.execute(
            """
            INSERT INTO scoring_costs
                (job_id, purpose, model, input_tokens, output_tokens, cost_usd, timestamp, provider)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                _DEMO_JOBS[i][0],  # job_id — reference first few demo rows
                purpose,
                model,
                in_tok,
                out_tok,
                0.0,  # $0 — ollama is free
                ts,
                "ollama",
            ),
        )


def _seed_onboarding_complete(conn: sqlite3.Connection) -> None:
    """Mark onboarding as complete so the app skips the setup wizard."""
    conn.execute("INSERT OR REPLACE INTO onboarding_state (id, onboarding_complete) VALUES (1, 1)")


def seed(target_dir: Path) -> None:
    """Run the full seed pipeline against *target_dir*.

    Idempotent: re-running resets to the clean seeded state.
    """
    _check_guard(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)

    _write_config(target_dir)

    db_path = str(target_dir / "jobs.db")
    _seed_db(db_path, target_dir)

    # Write sentinel last (after DB is known-good) so the guard fires correctly
    # on subsequent runs even if a previous run was interrupted mid-write.
    sentinel = target_dir / _SENTINEL
    sentinel.write_text(
        "Created by scripts/seed_demo_data.py — safe to delete this entire directory.\n",
        encoding="utf-8",
    )

    # Human-readable summary
    job_count = len(_DEMO_JOBS)
    apply_count = sum(1 for j in _DEMO_JOBS if _derive_classification(j[6]) == "apply")
    consider_count = sum(1 for j in _DEMO_JOBS if _derive_classification(j[6]) == "consider")
    reject_count = sum(1 for j in _DEMO_JOBS if _derive_classification(j[6]) in ("reject", "skip"))

    print(f"Seeded {job_count} jobs into {target_dir}")
    print(f"  apply={apply_count}  consider={consider_count}  other={reject_count}")
    print("  config.yaml written (all paid sources disabled)")
    print("  scoring_costs: 5 ollama rows @ $0.00")
    print()
    print("Boot the app with:")
    print(f'  $env:JOB_CANNON_USER_DATA_DIR = "{target_dir}"  # PowerShell')
    print("  # or:")
    print(f"  set JOB_CANNON_USER_DATA_DIR={target_dir}  # cmd.exe")
    print("  uv run job-cannon")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Seed a throwaway user-data dir with demo data for README recording."
    )
    parser.add_argument(
        "--dir",
        required=True,
        metavar="PATH",
        help="Path to the target directory (created if absent).",
    )
    args = parser.parse_args()
    seed(Path(args.dir))


if __name__ == "__main__":
    os.environ.setdefault("GSD_BACKUP_CONFIRMED", "1")
    main()
